### PR TITLE
removed individual match-ups from the console

### PR DESCRIPTION
**Pull request by lukassta**
With a growing amount of strategies the amount of match-ups in the console becomes cumbersome. I suggest removing them from the console because excel sheet is a way better way to analyze data.
(Will merge if both reviewrs agree)

### CODE REVIEW

**Review by LeMeowM — CHANGES_REQUESTED** [review]
yeah sounds right, can you also clean up the individual scores for every player too?

**Comment by lukassta** [comment]
> yeah sounds right, can you also clean up the individual scores for every player too?

Well those scores do not take up that much space and in my opinion they could stay.

**Comment by LeMeowM** [comment]
> > yeah sounds right, can you also clean up the individual scores for every player too?
> 
> Well those scores do not take up that much space and in my opinion they could stay.

maybe they should be formatted in a cleaner way thats not just all in a column, maybe only the top 3 and bottom 3 unless we tell it otherwise?

**Review by LeMeowM — APPROVED** [review]
looks good, approved

**Review by AugustusTheBirb — COMMENTED** [review]
nice, looks good

**Pull request merged**
